### ISSUE TITLE
Use batch requests in get_objects

### ISSUE THREAD

**Issue by vionemc** [mobolic/facebook-sdk#271] opened 2016-02-22 06:26 UTC
I want to make a bulk request using `get_objects`, but if some of the ID doesn't exist, even though other IDs exist, the whole bulk request fails. It's annoying.

When I run this: `graph.get_objects(ids=['maxlibin','upwork', 'watcfy'])`
Currently I'll just get error 803
`facebook.GraphAPIError: (#803) Cannot query users by their username (maxlibin)`

I hope you'll give response like:
```
{
'maxlibin': '(#803) Cannot query users by their username (maxlibin)',
'upwork':{}, #The successful result
'watcfy':{} #The successful result
}
```

**Comment by martey** [comment] 2016-02-23 17:40
Since this is partially a problem with the Graph API and not this particular library, I was going to advise you to report this upstream, but I see you already did at https://developers.facebook.com/bugs/1000666673351426/.

Facebook's suggestion to use [batch requests](https://developers.facebook.com/docs/graph-api/making-multiple-requests) is what I would have suggested as well. Feel free to submit a pull request making changes to `get_objects`.

**Comment by vionemc** [comment] 2016-02-24 03:14
OK! Well, I hope Facebook Team will hear my suggestion in the future. It will be nice to save rate limit

**Comment by vionemc** [comment] 2016-02-24 03:16
I don't think it's a good idea to change `get_objects` to batch request. Like what I said before, rate limit problem.

**Comment by martey** [comment] 2016-04-14 06:09
Closing, since adding support for batch requests to `get_objects` is a duplicate of #28 (which shouldn't cause rate limiting unlike you are using the API in a way that Facebook does not like).

**Closed by martey** 2016-04-14 06:09 UTC
Labels: duplicate
