### ISSUE TITLE
Add test users support

### ISSUE THREAD

**Issue by TechneLogosDev** [mobolic/facebook-sdk#393] opened 2017-10-13 03:39 UTC
Adding methods to get and manipulate test users would allow the sdk's users to more easily create tests by making test user operations more accessible. Implementing this feature would also allow us to write better and cleaner tests. I propose implementing a get_test_users method, an add_test_user method, and remove_test_user method.

**Comment by martey** [comment] 2017-10-14 12:22
This looks like a duplicate of #172.

**Closed by martey** 2017-10-14 12:22 UTC
